# Generated by Django 3.0.5 on 2020-05-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sul_clientes_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
