# Generated by Django 3.0.5 on 2020-05-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sul_clientes_cadastro', '0002_auto_20200504_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome_cliente',
            field=models.TextField(max_length=100),
        ),
    ]
