# Generated by Django 3.0.5 on 2020-05-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sul_clientes_cadastro', '0003_auto_20200504_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='detalhes_cliente',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_cliente',
            field=models.TextField(max_length=40),
        ),
    ]
