# Generated by Django 3.0.5 on 2020-05-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sul_clientes_cadastro', '0004_auto_20200504_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome_cliente',
            field=models.CharField(max_length=40),
        ),
    ]
