# Generated by Django 3.0.5 on 2020-05-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sul_clientes_cadastro', '0005_auto_20200504_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_publicacao',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_cliente',
            field=models.CharField(max_length=60),
        ),
    ]
