# Generated by Django 3.0.5 on 2020-05-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sul_clientes_cadastro', '0007_auto_20200505_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.BooleanField(choices=[(False, 'Pendente'), (True, 'Concluido')]),
        ),
    ]
