# Generated by Django 3.0.5 on 2020-05-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sul_clientes_cadastro', '0011_auto_20200506_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='anotacoes',
            field=models.TextField(max_length=200),
        ),
    ]
