# Generated by Django 3.0.5 on 2020-05-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sul_clientes_cadastro', '0013_auto_20200506_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='anotacoes',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='detalhes_cliente',
            field=models.CharField(max_length=200),
        ),
    ]
