# Generated by Django 3.0.5 on 2020-05-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sul_clientes_cadastro', '0014_auto_20200506_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='anotacoes',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='detalhes_cliente',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluido', 'Concluido')], max_length=255, verbose_name='Status'),
        ),
    ]
