# Generated by Django 3.0.5 on 2020-05-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sul_clientes_cadastro', '0016_auto_20200506_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
