# Generated by Django 3.0.5 on 2020-05-06 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sul_clientes_cadastro', '0021_auto_20200506_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='status_2',
            new_name='avaliacao',
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(choices=[('Barra do Ribeiro', 'Barra do Ribeiro'), ('Mariana Pimentel', 'Mariana Pimentel'), ('Douradilho', 'Douradilho'), ('Petim', 'Petim'), ('California City', 'California City'), ('N/D', 'N/D')], default='N/D', max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='edit_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
