# Generated by Django 3.0.5 on 2020-05-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sul_clientes_cadastro', '0022_auto_20200506_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='anotacoes',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='edit_data',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='logradouro',
        ),
        migrations.AddField(
            model_name='cliente',
            name='regiao_cliente',
            field=models.CharField(choices=[('Barra do Ribeiro', 'Barra do Ribeiro'), ('Mariana Pimentel', 'Mariana Pimentel'), ('Petim', 'Petim'), ('Passo da Estancia', 'Passo da Estancia'), ('Douradilho', 'Douradilho'), ('California City', 'California City'), ('N/D', 'N/D')], default='N/D', max_length=255, verbose_name='Cidade/Logradouro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='avaliacao',
            field=models.CharField(choices=[('Em analise', 'Em analise'), ('Concluido', 'Concluido'), ('Sem sinal', 'Sem sinal'), ('N/D', 'N/D')], default='N/D', max_length=255, verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='detalhes_cliente',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluido', 'Concluido')], max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(default=11),
        ),
    ]
