# Generated by Django 3.0.5 on 2020-05-06 23:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sul_clientes_cadastro', '0023_auto_20200506_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='avaliacao',
            new_name='avaliacao_localizacao',
        ),
        migrations.AddField(
            model_name='cliente',
            name='condicao_atendimento',
            field=models.TextField(default=None, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_edit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
