# Generated by Django 3.0.5 on 2020-05-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sul_clientes_cadastro', '0025_auto_20200507_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('Aguardando avaliação', 'Aguardando avaliação'), ('Concluido', 'Concluido')], max_length=255, verbose_name='Status'),
        ),
    ]
