# Generated by Django 3.0.8 on 2020-07-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sul_clientes_cadastro', '0027_auto_20200707_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_edit',
        ),
    ]
