# Generated by Django 3.0.8 on 2020-07-07 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centro_sul_clientes_cadastro', '0028_auto_20200707_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
