# Generated by Django 3.0.8 on 2020-07-07 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sul_clientes_cadastro', '0029_auto_20200707_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='publish',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
