# Generated by Django 3.0.8 on 2020-07-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sul_clientes_cadastro', '0030_auto_20200707_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='avaliacao_localizacao',
            field=models.CharField(choices=[('Em analise', 'Em analise'), ('Concluido', 'Concluido'), ('Sem sinal', 'Sem sinal')], default='Em analise', max_length=255, verbose_name='Avaliação'),
        ),
    ]
